### ISSUE TITLE
No page opens up?

### ISSUE THREAD

**Issue by Bazmundi** [urbica/gis-notebook#1]
Running on debian 9, using Docker version 18.09.3, build 774a1f4.

Running on laptop connected to wifi router (and therefore internet).

Runs up to present an url, but when I open url the browser reports:

This site can’t be reached 155c88092bab’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

Full startup message:
asterion@roam:~$ docker run -it --rm -p 8888:8888 urbica/gis-notebook                                   
/usr/local/bin/start-notebook.sh: ignoring /usr/local/bin/start-notebook.d/*

Container must be run with group "root" to update passwd file
Executing the command: jupyter notebook
[I 02:31:33.703 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 02:31:34.016 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 02:31:34.077 NotebookApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 02:31:34.077 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 02:31:34.098 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 02:31:34.098 NotebookApp] 0 active kernels
[I 02:31:34.098 NotebookApp] The Jupyter Notebook is running at:
[I 02:31:34.098 NotebookApp] http://155c88092bab:8888/?token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c
[I 02:31:34.099 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:31:34.099 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://155c88092bab:8888/?token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c&token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c

**Comment by stepankuzmin** [comment]
Thanks for the issue, @Bazmundi! It's a common problem, you can replace generated hostname with `localhost`, e.g. open 

```
http://localhost:8888/?token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c&token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c
```

instead of 

```
http://155c88092bab:8888/?token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c&token=d61fd77baab6d329d4965125ebbbd8436174c281f7711e8c
```

**Comment by Bazmundi** [comment]
Gotcha.

Although, I was hoping there was a docker-esque fix, so that the DNS on my
network would "know" how to resolve the address.  Probably something for
the docker forum.
